### ISSUE TITLE
Add even more items?

### ISSUE THREAD

**Issue by michaeljakob** [andmpel/MacOS-All-In-One-Update-Script#1]
Great idea! I just found this with google search by looking for a script that updates all software on my mac.

Some more ideas to add

- yarn
- softwareupdate -ia
- adobe
- different terminal commands and build chains

**Comment by andmpel** [comment]
- I've added yarn
- Softwareupdate -i -a was already in there.
- I couldn't find a way to update all adobe applications through bash. Were you referring to Adobe CC Apps? Or Flash, Reader, or anything else specifically?
- Can you please expand on what you mean by different commands and build chains?

**Comment by andmpel** [comment]
I'm going to close this issue. Thank you for the suggestions.
