### ISSUE TITLE
Plugin for Fish Shell

### ISSUE THREAD

**Issue by demartini** [andmpel/MacOS-All-In-One-Update-Script#4]
Hi,

First of all I would like to thank you for this wonderful script.

I recently migrated from `zsh` to `fish shell`, in [fish](https://fishshell.com/) I had several functions to make updates, but after finding your script I created a plugin for Fish Shell inspired by yours.

I hope you don't mind me sharing my contribution here.

[upmm.fish](https://github.com/demartini/upmm.fish)

**Comment by andmpel** [comment]
Really cool. Thanks for the kind words. This was one of my first projects. 

Never heard of fish shell. But thanks for sharing!
